###
GET http://localhost:4000/product-api/products
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9kdWN0SWQiOjEwMSwiaWF0IjoxNzczMzIzMDgwLCJleHAiOjE3NzMzMjY2ODB9.MuRhT9cs7CDv3gvBd9y2W-rmujyncu8ZYuTkUQsnsp8; Path=/; HttpOnly; SameSite=Lax
### Read a user by id
GET http://localhost:4000/product-api/products/101
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9kdWN0SWQiOjEwMSwiaWF0IjoxNzczMzIzMDgwLCJleHAiOjE3NzMzMjY2ODB9.MuRhT9cs7CDv3gvBd9y2W-rmujyncu8ZYuTkUQsnsp8; Path=/; HttpOnly; SameSite=Lax


### create new user
POST http://localhost:4000/product-api/products
Content-Type: application/json


{
    "productId":101,
    "productName":"laptop",
    "price":45000,
    "brand":"hp"
}


### update user
PUT http://localhost:4000/product-api/products/101
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9kdWN0SWQiOjEwMSwiaWF0IjoxNzczMzIzMDgwLCJleHAiOjE3NzMzMjY2ODB9.MuRhT9cs7CDv3gvBd9y2W-rmujyncu8ZYuTkUQsnsp8; Path=/; HttpOnly; SameSite=Lax



{
    
    "productId":101,
    "productName":"laptop",
    "price":40000,
    "brand":"hp"

    
}
###
POST http://localhost:4000/product-api/auth
Content-Type: application/json

{
    "productId":101,
    "productName":"laptop"
}




###
DELETE http://localhost:5000/product-api/products/101
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9kdWN0SWQiOjEwMSwiaWF0IjoxNzczMzIzMDgwLCJleHAiOjE3NzMzMjY2ODB9.MuRhT9cs7CDv3gvBd9y2W-rmujyncu8ZYuTkUQsnsp8; Path=/; HttpOnly; SameSite=Lax

